# Generated by Django 6.0.5 on 2026-05-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_child_photo'),
        ('schedule', '0002_event_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='children.child')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.event')),
            ],
            options={
                'unique_together': {('event', 'child')},
            },
        ),
    ]
