# Generated by Django 6.0.5 on 2026-05-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
