# Generated by Django 6.0.5 on 2026-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('squad', 'Squad'), ('personal', 'Personal')], default='personal', max_length=20),
        ),
    ]
