# Generated by Django 6.0.5 on 2026-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('муж', 'Муж'), ('жен', 'Жен')], max_length=10),
        ),
    ]
