# Generated by Django 6.0.5 on 2026-05-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_child_gender'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='group_name',
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='group.group'),
        ),
    ]
