# Generated by Django 6.0.5 on 2026-05-18 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_remove_child_group_name_child_group'),
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Муж'), ('female', 'Жен')], max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
        migrations.CreateModel(
            name='ChildParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('child', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='children.ChildParentRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
