# Generated by Django 6.0.5 on 2026-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_remove_child_parent_alter_child_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='children/'),
        ),
    ]
