# Generated by Django 6.0.5 on 2026-05-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_type_5e04e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_child_i_957430_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_created_b5b178_idx',
        ),
        migrations.RemoveField(
            model_name='news',
            name='child',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
    ]
