# Generated by Django 6.0.5 on 2026-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('educator', 'Educator'), ('medic', 'Medic'), ('admin', 'Admin')], default='parent', max_length=20),
        ),
    ]
